# Generated by Django 3.1.3 on 2020-11-28 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201128_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='users_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.users'),
        ),
    ]
